#!/usr/bin/env php
<?php

switch ($argv[0]) {
    case 'list':
        echo 'list command';
        break;

    default:
        echo 'No command detected.' . PHP_EOL;
        echo 'To list commands run:' . PHP_EOL;
        echo 'php ' . __FILE__ . ' list' . PHP_EOL;
        exit;
}